version: "3.9"
services:
  db:
    image: docker.io/library/postgres:latest
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: controlbox
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    security_opt:
      - "label=disable"
volumes:
  db_data:
    driver: local